name: catcareapp
description: A mobile app for cat care management using Flutter and Firebase.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  rxdart: ^0.27.7
  qr_flutter: ^4.1.0

  # ----------------------------
  # Core Functionality
  # ----------------------------
  table_calendar: ^3.0.9
  http: ^1.2.2
  geolocator: ^14.0.2
  url_launcher: ^6.3.0

  # ----------------------------
  # Firebase
  # ----------------------------
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3

  # ----------------------------
  # Media & Compression
  # ----------------------------
  image_picker: ^1.0.7
  flutter_image_compress: ^2.3.0

  # ----------------------------
  # Notifications & Utils
  # ----------------------------
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  uuid: ^4.5.1
  permission_handler: ^11.3.0
  android_intent_plus: ^5.1.0

  # ----------------------------
  # UI & State
  # ----------------------------
  provider: ^6.1.2
  flutter_hooks: ^0.21.3+1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo.jpg
    - images/logo1.png
    - images/google.png
    - images/google1.png
