// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP9y5eX4WI5Viz6FtVdh-oumWaQC10vHQ',
    appId: '1:925323016359:web:2af85d9ae811b15373c382',
    messagingSenderId: '925323016359',
    projectId: 'catcareapp-fce59',
    authDomain: 'catcareapp-fce59.firebaseapp.com',
    storageBucket: 'catcareapp-fce59.firebasestorage.app',
    measurementId: 'G-L8G8KN6TRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_IdBKqHR4o042Q4DQOdcxkMpKL208J4',
    appId: '1:925323016359:android:846fcdca471ea18c73c382',
    messagingSenderId: '925323016359',
    projectId: 'catcareapp-fce59',
    storageBucket: 'catcareapp-fce59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyzPblArK-EJj5Ay8psZw-UEERjpNQFgs',
    appId: '1:925323016359:ios:7b10c6724670102d73c382',
    messagingSenderId: '925323016359',
    projectId: 'catcareapp-fce59',
    storageBucket: 'catcareapp-fce59.firebasestorage.app',
    iosBundleId: 'com.example.catcareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyzPblArK-EJj5Ay8psZw-UEERjpNQFgs',
    appId: '1:925323016359:ios:7b10c6724670102d73c382',
    messagingSenderId: '925323016359',
    projectId: 'catcareapp-fce59',
    storageBucket: 'catcareapp-fce59.firebasestorage.app',
    iosBundleId: 'com.example.catcareapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP9y5eX4WI5Viz6FtVdh-oumWaQC10vHQ',
    appId: '1:925323016359:web:af0e7f8195e0084c73c382',
    messagingSenderId: '925323016359',
    projectId: 'catcareapp-fce59',
    authDomain: 'catcareapp-fce59.firebaseapp.com',
    storageBucket: 'catcareapp-fce59.firebasestorage.app',
    measurementId: 'G-07MGQ75JGS',
  );
}
